package br.com.xti.poo.metodos.abstratos;

public class ClassesEMetodosAbstratos {

	//CLASSE GENERICA
	//SUPER TIPO, SUPER CLASSE, CLASSE MAE, CLASSE PAI
	//ANIMAL
	
	//CLASSE CONCRETA
	//SUB TIPO, SUB CLASSE, CLASSE FILHA
	//CACHORRO, GALINHA
	
	
	//EM ALGUM MOMENTO SERÁ NECESSÁRIO INSTANCIAR ANIMAL, OU SOMENTE GALINHA, CACHORRO... OS ANIMAIS
	// ESPECIFICOS
	
	//CLASSES ABSTRATAS(SUPERCLASSES) NÃO PODEM SER INSTANCIADAS, SOMENTE PODEM SER ESTENDIDAS, SERVEM EXATAMENTE PARA DEFINIR METODOS ABSTRATOS QUE SERÃO
	//IMPLEMENTADOS(SOBREESCRITOS) EM CLASSES CONCRETAS(SUBCLASSES) OBRIGATORIAMENTE
	//A MENOS QUE A CLASSE QUE ESTIVER ESTENDENDO A CLASSE ABSTRATA TAMBEM FOR UMA CLASSE ABSTRATA.
	
	//AS CLASSES ABSTRATAS DEVEM SER IMPLEMENTADAS PELAS CLASSES CONCRETAS
	
	
	
	
}
